### ISSUE TITLE
错了一个符号

### ISSUE THREAD

**Issue by sq800** [CiroLee/tiny-lorem#1]
文档 ：`/docs/api/texts.md` 中
![image](https://user-images.githubusercontent.com/63217984/188606779-644393a8-62c8-422d-9823-48f95202e19d.png)

**Comment by CiroLee** [comment]
> 文档 ：`/docs/api/texts.md` 中 ![image](https://user-images.githubusercontent.com/63217984/188606779-644393a8-62c8-422d-9823-48f95202e19d.png)

thks for issues!
